//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsLauncher.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AsLauncher.Resources.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Corrupted.
        /// </summary>
        public static string ButtonCorrupted {
            get {
                return ResourceManager.GetString("ButtonCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Install.
        /// </summary>
        public static string ButtonInstall {
            get {
                return ResourceManager.GetString("ButtonInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Installed.
        /// </summary>
        public static string ButtonInstalled {
            get {
                return ResourceManager.GetString("ButtonInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Installing.
        /// </summary>
        public static string ButtonInstalling {
            get {
                return ResourceManager.GetString("ButtonInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Launch.
        /// </summary>
        public static string ButtonLaunch {
            get {
                return ResourceManager.GetString("ButtonLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reinstall.
        /// </summary>
        public static string ButtonReinstall {
            get {
                return ResourceManager.GetString("ButtonReinstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove.
        /// </summary>
        public static string ButtonRemove {
            get {
                return ResourceManager.GetString("ButtonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Removing.
        /// </summary>
        public static string ButtonRemoving {
            get {
                return ResourceManager.GetString("ButtonRemoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restore.
        /// </summary>
        public static string ButtonRestore {
            get {
                return ResourceManager.GetString("ButtonRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unavailable.
        /// </summary>
        public static string ButtonUnavailable {
            get {
                return ResourceManager.GetString("ButtonUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Configs.
        /// </summary>
        public static string MainLabelsConfigs {
            get {
                return ResourceManager.GetString("MainLabelsConfigs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на General.
        /// </summary>
        public static string MainLabelsGeneral {
            get {
                return ResourceManager.GetString("MainLabelsGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Modpacks.
        /// </summary>
        public static string MainLabelsModpacks {
            get {
                return ResourceManager.GetString("MainLabelsModpacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vanilla.
        /// </summary>
        public static string MainLabelsVanilla {
            get {
                return ResourceManager.GetString("MainLabelsVanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Alpha.
        /// </summary>
        public static string MinecraftVersionAlpha {
            get {
                return ResourceManager.GetString("MinecraftVersionAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Beta.
        /// </summary>
        public static string MinecraftVersionBeta {
            get {
                return ResourceManager.GetString("MinecraftVersionBeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Release.
        /// </summary>
        public static string MinecraftVersionRelease {
            get {
                return ResourceManager.GetString("MinecraftVersionRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Example: 1.21.1 / 1 21 1 / 1211.
        /// </summary>
        public static string MinecraftVersionSearchExample {
            get {
                return ResourceManager.GetString("MinecraftVersionSearchExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minecraft Versions.
        /// </summary>
        public static string MinecraftVersionsList {
            get {
                return ResourceManager.GetString("MinecraftVersionsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Snapshot.
        /// </summary>
        public static string MinecraftVersionSnapshot {
            get {
                return ResourceManager.GetString("MinecraftVersionSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на no desc.
        /// </summary>
        public static string PagespaceGeneralDesc {
            get {
                return ResourceManager.GetString("PagespaceGeneralDesc", resourceCulture);
            }
        }
    }
}
